apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  schedule: "0 * * * *" # every hour at 00
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:  
          initContainers:
          - name: {{ .Name }}-init
              image: {{ .InitImage }}
              imagePullPolicy: Always
              command: 
              - "/bin/runner"
              - '{{ .Jsn }}'
              volumeMounts:
              - name: data-volume
              mountPath: /data 
          containers:
          - name: {{ .Name }}
              image: {{ .Image }}
              imagePullPolicy: Always
              command: 
              - "/bin/runner"
              - '{{ .Jsn }}'
              volumeMounts:
              - name: data-volume
              mountPath: /data
          volumes:
          - name: data-volume
            emptyDir: {}
          restartPolicy: Never
      backoffLimit: 0
      ttlSecondsAfterFinished: 180 
