apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Name }}-{{ .Resource }}"
  namespace: {{ .Namespace }}
spec:
  schedule: "{{ .Schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            testkube: cronjob 
        spec:
          containers:
          - name: curlimage
            image: curlimages/curl
            imagePullPolicy: Always
            command:
            - sh
            - -c
            args:
            - curl -X POST -H "Content-Type: application/json" -d '{{ .Data }}' "http://{{ .ServiceName }}:{{ .ServicePort}}/v1/{{ .Resource }}/{{ .Name }}/executions"
          restartPolicy: Never
      backoffLimit: 0
      ttlSecondsAfterFinished: 180
