apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  ttlSecondsAfterFinished: 180  
  template:
    spec:
      initContainers:
      - name: {{ .Name }}-init
        image: {{ .InitImage }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data 
      containers:
      - name: {{ .Name }}
        image: {{ .Image }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
