apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
spec:
  template:
    spec:
      initContainers:
      - name: {{ .Name }}-init
        image: {{ .InitImage }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data 
      containers:
      - name: {{ .Name }}
        image: {{ .Image }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Never
      {{- if gt (len .ImagePullSecrets) 0 }}
      imagePullSecrets:
      {{- range $secret := .ImagePullSecrets}}
      - name: {{ $secret -}}
      {{- end}}
      {{- end}}
  backoffLimit: 0
  ttlSecondsAfterFinished: 180  
