apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Name }}-scraper
  namespace: {{ .Namespace }}
spec:
  {{- if gt .ActiveDeadlineSeconds 0 }}
  activeDeadlineSeconds: {{ .ActiveDeadlineSeconds }}
  {{- end }}
  template:
    spec:
      containers:
      - name: {{ .Name }}-scraper
        {{- if .Registry }}
        image: {{ .Registry }}/{{ .ScraperImage }}
        {{- else }}
        image: {{ .ScraperImage }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/runner"
          - '{{ .Jsn }}'
        {{- if .ArtifactRequest }}
          {{- if .ArtifactRequest.VolumeMountPath }}
        volumeMounts:
          - name: artifact-volume
            mountPath: {{ .ArtifactRequest.VolumeMountPath }}
          {{- end }}
        {{- end }}
      {{- if .ArtifactRequest }}
        {{- if and .ArtifactRequest.VolumeMountPath .ArtifactRequest.StorageClassName }}
      volumes:
        - name: artifact-volume
          persistentVolumeClaim:
            claimName: {{ .Name }}-pvc
        {{- end }}
      {{- end }}
      restartPolicy: Never
      {{- if .ServiceAccountName }}
      serviceAccountName: {{ .ServiceAccountName }}
      {{- end }}
      {{- if gt (len .ImagePullSecrets) 0 }}
      imagePullSecrets:
      {{- range $secret := .ImagePullSecrets }}
      - name: {{ $secret -}}
      {{- end }}
      {{- end }}
  backoffLimit: 0
  ttlSecondsAfterFinished: {{ .DelaySeconds }}
