apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Name }}-pvc
  namespace: {{ .Namespace }}
spec:
  storageClassName: {{ .ArtifactRequest.StorageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
