{{- if not (.Capabilities.APIVersions.Has "tests.testkube.io/v1") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "testkube-operator.namespace" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    job-name: {{ include "testkube-operator.namespace" . }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "testkube-operator.namespace" . }}
      labels:
        app.kubernetes.io/component: testkube-operator
        app.kubernetes.io/name: {{ include "testkube-operator.namespace" . }}
    spec:
      serviceAccountName: {{ include "testkube-operator.namespace" . }}
      containers:
      - name: kubectl
        image: "k8s.gcr.io/hyperkube:v1.12.1"
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/bash
        - -c
        - >
            export namespace=$(kubectl get namespaces | grep {{ include "testkube-operator.namespace" . }} | awk '{print $1}');
              if [ "$namespace" == "{{ include "testkube-operator.namespace" . }}" ];
                then exit 0;
              else
                kubectl create namespace {{ include "testkube-operator.namespace" . }};
              fi
      restartPolicy: Never
{{ end }}