apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "testkube-operator.namespace" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    job-name: {{ include "testkube-operator.namespace" . }}
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "testkube-operator.namespace" . }}
      labels:
        app.kubernetes.io/component: testkube-operator
        app.kubernetes.io/name: {{ include "testkube-operator.namespace" . }}
    spec:
      serviceAccountName: {{ include "testkube-operator.namespace" . }}
      containers:
      - name: kubectl
        image: {{ include "global.images.image" (dict "imageRoot" .Values.preUpgrade.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.preUpgrade.image.pullPolicy }}
        command:
        - /bin/bash
        - -c
        - >
            export namespace=$(kubectl get namespaces | grep {{ include "testkube-operator.namespace" . }} | awk '{print $1}' | head -n1 );
              if [ "$namespace" == "{{ include "testkube-operator.namespace" . }}" ];
                then echo "Namespace already exists";
              else
                kubectl create namespace {{ include "testkube-operator.namespace" . }};
              fi
      restartPolicy: Never
