{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "testkube-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---

{{- if and .Values.webhook.enabled .Values.webhook.patch.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testkube-operator.webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "testkube-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.webhook.patch.serviceAccount.annotations }}
    {{- toYaml .Values.webhook.patch.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  {{- end }}
