{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  {{- if .Values.webhook.annotations }}
  annotations: {{ toYaml .Values.webhook.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "testkube-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    {{- with .Values.webhook.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.webhook.name }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "testkube-operator.webhookServiceName" . }}
      namespace: {{ .Release.Namespace }}
      path: /validate-tests-testkube-io-v1-testtrigger
  failurePolicy: Fail
  name: vtesttrigger.kb.io
  rules:
  - apiGroups:
    - tests.testkube.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - testtriggers
  sideEffects: None
{{- end }}
