{{- if .Values.cliIngress.enabled -}}
  {{- $fullName := include "testkube-api.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if and .Values.cliIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.cliIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.cliIngress.annotations "kubernetes.io/ingress.class" .Values.cliIngress.className}}
  {{- end }}
  {{- end }}
  {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else -}}
apiVersion: extensions/v1
  {{- end }}
kind: Ingress
metadata:
  name: cli-{{ $fullName }}-{{ .Release.Name }}
  labels:
    {{- include "global.labels.standard" . | nindent 4 }}
      {{- if .Values.uiIngress.labels }}
      {{- include "global.tplvalues.render" ( dict "value" .Values.uiIngress.labels "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.globalLabels }}
      {{- include "global.tplvalues.render" ( dict "value" .Values.globalLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- with .Values.cliIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
      {{- end }}
      {{- if .Values.globalAnnotations }}
      {{- include "global.tplvalues.render" ( dict "value" .Values.globalAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
spec:
  {{- if and .Values.cliIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.cliIngress.className }}
  {{- end }}
  {{- if .Values.cliIngress.tls }}
  tls:
    {{- if .Values.cliIngress.tlsenabled }}
      {{- range .Values.cliIngress.tls }}
      - hosts:
          {{- range .hosts }}
          - {{ . | quote }}
          {{- end }}
        secretName: {{ .secretName }}
      {{- end }}
      {{- end }}
  {{- end }}
  rules:
    {{- range .Values.cliIngress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.cliIngress.path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}