{{ if .Values.rbac.create }}

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: executors-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: executors-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: jobs-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobs-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: scripts-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: script-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: tests-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: secrets-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: testsuites-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testsuite-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: webhooks-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: configmaps-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmaps-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: testsources-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testsource-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: testtriggers-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testtriggers-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: watchers-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watchers-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: persistentvolumeclaims-crb-{{ .Release.Name }}
  labels: {{- include "testkube-api.labels" . | nindent 4 }}
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations}}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: persistentvolumeclaims-cluster-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
