{{ if .Values.rbac.createRoleBindings }}

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: executors-crb-{{ .Release.Name }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executors-role-{{ .Release.Name }}-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: jobs-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: scripts-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: script-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: tests-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: secrets-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: testsuites-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testsuite-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: webhooks-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: configmaps-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmaps-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: testsources-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testsource-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: testtriggers-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testtriggers-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: watchers-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watchers-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: persistentvolumeclaims-crb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: persistentvolumeclaims-role-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "testkube-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
