{{ if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "testkube-api.fullname" . }}-servicemonitor
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "testkube-api.fullname" . }}
{{ end }}