{{ if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "testkube-api.fullname" . }}-servicemonitor
  labels: {{- include "testkube-api.monitoring" . | nindent 4 }}
    {{- if .Values.monitoringLabels }}
    {{- include "testkube-api.render" ( dict "value" .Values.monitoringLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "testkube-api.fullname" . }}
{{ end }}