{{- if .Values.uiIngress.enabled -}}
{{- $fullName := include "testkube-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.uiIngress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.uiIngress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.uiIngress.annotations "kubernetes.io/ingress.class" .Values.uiIngress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: ui-{{ $fullName }}-{{ .Release.Name }}
  labels:
    {{- include "testkube-api.labels" . | nindent 4 }}
  {{- with .Values.uiIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.uiIngress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.uiIngress.className }}
  {{- end }}
  {{- if .Values.uiIngress.tls }}
  tls:
    {{- if .Values.uiIngress.tlsenabled }}
    {{- range .Values.uiIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.uiIngress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.uiIngress.path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}