---
apiVersion: gateway.kusk.io/v1alpha1
kind: EnvoyFleet
metadata:
  name: {{ include "kusk-gateway-envoyfleet.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway-envoyfleet.labels" . | nindent 4 }}
spec:
  default: {{ .Values.default }}
  size: {{ .Values.size }}
  image: {{ .Values.image }}
  service:
{{ toYaml .Values.service |indent 4 }}

{{- if .Values.resources }}
  resources:
{{ toYaml .Values.resources |indent 4 }}
{{- end -}}

{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations |indent 4 }}
{{- end -}}

{{- if .Values.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.nodeSelector |indent 4 }}
{{- end -}}

{{- if .Values.tolerations }}
  tolerations:
{{ toYaml .Values.tolerations |indent 4 }}
{{- end -}}

{{- if .Values.affinity }}
  affinity:
{{ toYaml .Values.affinity |indent 4 }}
{{- end -}}

{{- if .Values.accesslog }}
  accesslog:
{{ toYaml .Values.accesslog |indent 4 }}
{{- end }}

{{- if .Values.terminationGracePeriodSeconds }}
  terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- end }}

{{- if .Values.tls }}
  tls:
{{ toYaml .Values.tls |indent 4 }}
{{- end }}
