{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kusk-gateway-manager
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kusk-gateway-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ template "kusk-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kusk-gateway-envoyfleet-manager
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kusk-gateway-envoyfleet-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ template "kusk-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kusk-gateway-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kusk-gateway-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ template "kusk-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}

{{- end -}}
