---
apiVersion: v1
kind: Service
metadata:
  name: kusk-gateway-xds-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: xds-service
spec:
  type: {{ .Values.xdsService.type }}
  ports:
    - port: {{ .Values.xdsService.port }}
      targetPort: xds
      protocol: TCP
      name: xds
  selector:
    {{- include "kusk-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "kusk-gateway-validator-service"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: validator-service
spec:
  type: {{ .Values.validatorService.type }}
  ports:
    - port: {{ .Values.validatorService.port }}
      targetPort: validator
      protocol: TCP
      name: validator
  selector:
    {{- include "kusk-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "kusk-gateway-auth-service"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  type: {{ .Values.authService.type }}
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: auth
      protocol: TCP
      name: auth
  selector:
    {{- include "kusk-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kusk-gateway.webhooksServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: kusk-gateway-webhooks-service
spec:
  type: {{ .Values.webhooks.service.type }}
  ports:
    - port: {{ .Values.webhooks.service.port }}
      targetPort: webhook-server
      protocol: TCP
      name: webhook-server
  selector:
    {{- include "kusk-gateway.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kusk-gateway.agentServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kusk-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-service
spec:
  ports:
    - port: {{ .Values.agentService.port }}
      name: agent-config
      targetPort: agent-config
  selector:
    {{- include "kusk-gateway.selectorLabels" . | nindent 4 }}
