{{- if .Values.preUpgradeHookNATS.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.preUpgradeHookNATS.name }}"
  labels:
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}

{{- if .Values.preUpgradeHookNATS.serviceAccount.create }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.preUpgradeHookNATS.name }}"
  labels:
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale", "statefulsets"]
    verbs: ["create","delete","get","list","patch","update","watch"]
{{- end }}

{{- if .Values.preUpgradeHookNATS.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.preUpgradeHookNATS.name }}"
  labels:
    {{- if .Values.global.labels }}
    {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.preUpgradeHookNATS.name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.preUpgradeHookNATS.name }}"
{{- end }}
