{{- if .Values.preUpgradeHook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.preUpgradeHook.name }}"
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  {{- end }}

---
{{- if .Values.preUpgradeHook.serviceAccount.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.preUpgradeHook.name }}"
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["create","delete","get","list","patch","update","watch"]
{{- end }}

---
{{- if .Values.preUpgradeHook.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.preUpgradeHook.name }}"
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.preUpgradeHook.name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.preUpgradeHook.name }}"
{{- end }}
