# agent settings for dev enterprise
global:
  features:
    logsV2: true

testkube-api:
  cloud:
    url: agent.enterprise.testkube.dev:443
    key: "" # Required
    orgId: "" # Required
    envId: "" # Required
  minio:
    enabled: false
mongodb:
  enabled: false

testkube-dashboard:
  enabled: false

nats:
  nats:
    jetstream:
      enabled: true

  natsBox:
    enabled: false

testkube-logs:
  autoscaling:
    enabled: false
  replicaCount: 1
  pro:
    url: logs.enterprise.testkube.dev:443
    key: "" #Required
