# agent settings for in cluster only agent on enterprise installation
global:
  features:
    logsV2: true

testkube-api:
  cloud:
    tls.enabled: false
    url: testkube-enterprise-api.testkube-enterprise.svc.cluster.local:8089
    key: "" # Required
    orgId: "" # Required
    envId: "" # Required
  minio:
    enabled: false
mongodb:
  enabled: false

nats:
  nats:
    jetstream:
      enabled: true

  natsbox:
    enabled: false

testkube-logs:
  autoscaling:
    enabled: false
  replicaCount: 1
  pro:
    url: testkube-enterprise-logs-service.testkube-enterprise.svc.cluster.local:8089
    key: "" #Required
    tls.enabled: false
