apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Name }}"
  namespace: {{ .Namespace }}
  labels:
    testkube: {{ .ResourceURI }}
{{- if .ArgoCDSync }}
  ownerReferences:
  - apiVersion: tests.testkube.io/{{ .Version }}
    kind: {{ .Resource }}
    name: {{ .Id }}
    uid: {{ .UID }}
{{- end }}
spec:
  schedule: "{{ .Schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curlimage
            {{- if .Registry }}
            image: {{ .Registry }}/curlimages/curl
            {{- else }}
            image: curlimages/curl
            {{- end }}
            imagePullPolicy: IfNotPresent
            command:
            - sh
            - -c
            args:
            - 'curl -X POST -H "Content-Type: application/json" -d ''{{ .Data }}'' "http://{{ .ServiceName }}:{{ .ServicePort}}/v1/{{ .ResourceURI }}/{{ .Id }}/executions"'
          restartPolicy: Never
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      backoffLimit: 0
      ttlSecondsAfterFinished: 180
