apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest.fullname" . }}
  labels:
    {{- include "tracetest.labels" . | nindent 4 }}
data:
  config.yaml: |-
    postgresConnString: "host={{ include "tracetest.postgresql.fullname" . }} user={{.Values.postgresql.auth.username}} password={{.Values.postgresql.auth.password}}  port=5432 sslmode=disable"
    {{ if eq .Values.traceBackend "jaeger" }}
    jaegerConnectionConfig:
      {{- toYaml .Values.jaegerConnectionConfig | nindent 6 }}
    {{ end}} 
    {{ if eq .Values.traceBackend "tempo" }}
    tempoConnectionConfig:
      {{- toYaml .Values.tempoConnectionConfig | nindent 6 }}
    {{ end}} 

---
