{{- if not .Values.configMapOverride }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest.fullname" . }}
  labels:
    {{- include "tracetest.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- if .Values.postgresql.enabled }}
    postgres:
      host: {{ include "tracetest.postgresql.fullname" . }}
      user: {{.Values.postgresql.auth.username}}
      password: {{.Values.postgresql.auth.password}}
      port: 5432
      params: sslmode=disable
    {{- end }}
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    server:
      {{- toYaml .Values.server | nindent 6 }}
  provisioning.yaml: |-
    {{- toYaml .Values.provisioning | nindent 4 }}
---
{{- end }}
