apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest.fullname" . }}
  labels:
    {{- include "tracetest.labels" . | nindent 4 }}
data:
  config.yaml: |-
    poolingConfig:
      {{- toYaml .Values.poolingConfig | nindent 6 }}
    googleAnalytics:
      enabled: {{.Values.analytics.enabled}}
    postgresConnString: "host={{ include "tracetest.postgresql.fullname" . }} user={{.Values.postgresql.auth.username}} password={{.Values.postgresql.auth.password}}  port=5432 sslmode=disable"
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    server:
      {{- toYaml .Values.server | nindent 6 }}

---
