apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracetest.fullname" . }}
  labels:
    {{- include "tracetest.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 21321
      targetPort: otlp
      protocol: TCP
      name: otlp
  selector:
    {{- include "tracetest.selectorLabels" . | nindent 4 }}
