apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kusk-gateway-api.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "kusk-gateway-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kusk-gateway-api.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kusk-gateway-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
