#!/bin/bash
set -e
set -o pipefail

# Script to update CRDs from testkube-operator repository
# Usage: ./scripts/update_crds.sh

REPO_URL="https://raw.githubusercontent.com/kubeshop/testkube-operator/main/config/crd/bases"
CHART_DIR="charts/testkube-operator/templates"
TEMP_DIR=$(mktemp -d)

echo "🔄 Updating CRDs from testkube-operator repository..."

# List of CRD files to download (excluding deprecated ones)
CRD_FILES=(
    "executor.testkube.io_webhooks.yaml"
    "executor.testkube.io_webhooktemplates.yaml"
    "tests.testkube.io_testtriggers.yaml"
    "testworkflows.testkube.io_testworkflowexecutions.yaml"
    "testworkflows.testkube.io_testworkflows.yaml"
    "testworkflows.testkube.io_testworkflowtemplates.yaml"
)

# Deprecated CRDs (not updated by this script)
DEPRECATED_CRDS=(
    "executor.testkube.io_executors.yaml"
    "tests.testkube.io_scripts.yaml"
    "tests.testkube.io_templates.yaml"
    "tests.testkube.io_testexecutions.yaml"
    "tests.testkube.io_tests.yaml"
    "tests.testkube.io_testsources.yaml"
    "tests.testkube.io_testsuiteexecutions.yaml"
    "tests.testkube.io_testsuites.yaml"
)

# Function to wrap CRD with Helm conditional and auto-update comment
wrap_crd() {
    local file=$1
    local output_file=$2
    
    echo "{{/*" > "$output_file"
    echo "AUTO-GENERATED: This CRD is automatically updated by 'make crds'." >> "$output_file"
    echo "Do not edit this file directly." >> "$output_file"
    echo "*/}}" >> "$output_file"
    echo "{{- if .Values.installCRD }}" >> "$output_file"
    cat "$file" >> "$output_file"
    echo "{{- end }}" >> "$output_file"
}

# Download and process each CRD file
for crd_file in "${CRD_FILES[@]}"; do
    echo "📥 Downloading $crd_file..."
    
    # Download the CRD file
    if curl -fsSL "$REPO_URL/$crd_file" -o "$TEMP_DIR/$crd_file"; then
        echo "✅ Downloaded $crd_file"
        
        # Wrap with Helm conditional and save to chart templates
        wrap_crd "$TEMP_DIR/$crd_file" "$CHART_DIR/$crd_file"
        echo "✅ Updated $CHART_DIR/$crd_file"
    else
        echo "❌ Failed to download $crd_file"
        exit 1
    fi
done

# Clean up
rm -rf "$TEMP_DIR"

echo "🎉 All CRDs updated successfully!"
echo ""
echo "📋 Updated files:"
for crd_file in "${CRD_FILES[@]}"; do
    echo "  - $CHART_DIR/$crd_file"
done
echo ""
echo "⚠️  Deprecated CRDs (not updated):"
for crd_file in "${DEPRECATED_CRDS[@]}"; do
    echo "  - $CHART_DIR/$crd_file"
done
echo ""
echo "💡 Don't forget to:"
echo "  1. Review the changes with 'git diff'"
echo "  2. Test the chart with 'helm lint ./charts/testkube-operator'"
echo "  3. Update the chart version if needed"
