{{- if .Values.global.testWorkflows.createServiceAccountTemplates }}
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: serviceaccount--fullaccess
spec:
  pod:
    serviceAccountName: {{ include "testkube-api.serviceAccountName" . }}
{{- end }}
