apiVersion: v2
name: testkube-crds
description: A Helm chart for the TestKube CRDs
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: global
    version: 0.1.3
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
