name: Lint
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  chart-test:
    name: Helm Template
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.1

      - name: Dependency build
        run: |
          helm dependency build ./charts/testkube

      - name: Helm Lint
        run: |
          helm lint ./charts/testkube

      - name: Helm Template
        run: |
          helm template ./charts/testkube
