name: Releasing Testkube Helm charts to Stage k8s Cluster.

concurrency: develop_cluster

on:
  push:
    paths:
      - "charts/testkube/values-stage.yaml"
    branches:
      - develop

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME_DEVELOP }} # Add your cluster name here.
  GKE_ZONE: ${{ secrets.GKE_ZONE_DEVELOP }} # Add your cluster zone here.
  DEPLOYMENT_NAME: testkube-integration # Add your deployment name here.
  ENV: stage


jobs:
  release_charts_if_image_updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: |-
          gcloud --quiet auth configure-docker

      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Installing repositories
        run: |
          helm repo add bitnami https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami

      - name: Get image tag of Testkube APi, Dashboard, Operator
        id: vars
        run: |
          echo ::set-output name=api_image_tag::$(kubectl get deployment testkube-api-server -o=jsonpath='{$.spec.template.spec.containers[:1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1
          echo ::set-output name=operator_image_tag::$(kubectl get deployment testkube-operator-controller-manager -o=jsonpath='{$.spec.template.spec.containers[1].image}' -n testkube | awk -F':' '{print $2}') || exit 1
          echo ::set-output name=dashboard_image_tag::$(kubectl get deployment testkube-dashboard -o=jsonpath='{$.spec.template.spec.containers[:1].image}' -n ${{ env.DEPLOYMENT_NAME }} | awk -F':' '{print $2}') || exit 1

      - name: Deploy helm chart to Develop Cluster
        run: |
          helm dependency update ./charts/testkube
          helm upgrade --debug --install --atomic --timeout 180s testkube ./charts/testkube --namespace ${{ env.DEPLOYMENT_NAME }} --create-namespace  --values ./charts/testkube/values-${{ env.ENV }}.yaml --set testkube-operator.image.tag=${{ steps.vars.outputs.operator_image_tag }} --set testkube-dashboard.image.tag=${{ steps.vars.outputs.dashboard_image_tag }} --set testkube-api.image.tag=${{ steps.vars.outputs.api_image_tag }} --set testkube-api.multinamespace.enabled=true --set testkube-operator.enabled=false

  notify_slack_if_deploy_stage_succeeds:
    runs-on: ubuntu-latest
    needs: release_charts_if_image_updated
    steps:
      - name: Slack Notification if the helm release deployment to ${{ env.GKE_CLUSTER_NAME }} GKE into ${{ env.DEPLOYMENT_NAME }} namespace succeeded.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testkube-logs
          SLACK_COLOR: ${{ needs.release_charts_if_image_updated.result }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Helm chart release successfully deployed to ${{ env.GKE_CLUSTER_NAME }} GKE into ${{ env.DEPLOYMENT_NAME }} namespace :party_blob:!
          SLACK_USERNAME: GitHub
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Kubeshop --> TestKube"

  notify_slack_if_deploy_stage_failed:
    runs-on: ubuntu-latest
    needs: release_charts_if_image_updated
    if: always() && (needs.release_charts_if_image_updated.result == 'failure')
    steps:
      - name: Slack Notification if the helm release deployment to ${{ env.GKE_CLUSTER_NAME }} GKE into ${{ env.DEPLOYMENT_NAME }} namespace failed.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testkube-logs
          SLACK_COLOR: ${{ needs.release_charts_if_image_updated.result }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Helm chart release failed to deploy to ${{ env.GKE_CLUSTER_NAME }} GKE into ${{ env.DEPLOYMENT_NAME }} namespace :boom:!
          SLACK_USERNAME: GitHub
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Kubeshop --> TestKube"

  test_suite_run:
    name: test suite for GKE cluster
    runs-on: ubuntu-latest
    needs: release_charts_if_image_updated
    steps:
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Install testkube kubectl plugin and disable telemetry
        run: bash <(curl -sSLf https://get.testkube.io) beta && kubectl testkube disable telemetry --namespace ${{ env.DEPLOYMENT_NAME }}

      - name: Checkout tests from main Testkube repo
        uses: actions/checkout@v3
        with:
          repository: kubeshop/testkube
          path: testkube-repo

      - name: Executor tests - delete/create/schedule all executor tests
        working-directory: ./testkube-repo
        run: chmod +x ./test/scripts/executor-tests/run.sh && ./test/scripts/executor-tests/run.sh -d -c -s -n ${{ env.DEPLOYMENT_NAME }} # (delete, create, schedule) - don't execute

      - name: (Re)create Postman Sanity test (with CLI)
        working-directory: ./testkube-repo
        run: |-
          # enabling debug mode
          set -x
          kubectl delete test sanity --ignore-not-found=true --namespace ${{ env.DEPLOYMENT_NAME }}
          kubectl delete secret sanity-secrets --ignore-not-found=true --namespace ${{ env.DEPLOYMENT_NAME }}
          kubectl testkube create test -f ./test/postman/TestKube-Sanity.postman_collection.json --name sanity --type postman/collection -v api_uri=http://testkube-api-server:8088 -v test_api_uri=http://testkube-api-server:8088 -v test_type=postman/collection -v test_name=fill-me -v execution_name=fill-me --namespace ${{ env.DEPLOYMENT_NAME }}

      - name: Run Postman sanity tests
        run: kubectl testkube run test sanity -f --git-branch develop --namespace ${{ env.DEPLOYMENT_NAME }}

      - name: (Re)create Dashboard E2E tests (from CRD)
        working-directory: ./testkube-repo
        run: |-
          # enabling debug mode
          set -x
          kubectl delete test dashboard-e2e-tests --ignore-not-found=true --namespace ${{ env.DEPLOYMENT_NAME }}
          kubectl apply -f ./test/dashboard-e2e/crd/crd.yaml --namespace ${{ env.DEPLOYMENT_NAME }}

      - name: (Re)create staging testsuite
        working-directory: ./testkube-repo
        run: |-
          # enabling debug mode
          set -x
          kubectl delete testsuite staging-testsuite --ignore-not-found=true --namespace ${{ env.DEPLOYMENT_NAME }}
          kubectl testkube create testsuite -f ./test/suites/staging-testsuite.json --name staging-testsuite --namespace ${{ env.DEPLOYMENT_NAME }}

      - name: Run staging testsuite
        run: kubectl testkube run testsuite staging-testsuite -f --git-branch develop --namespace ${{ env.DEPLOYMENT_NAME }}

  notify_slack_if_test_suite_stage_succeeds:
    runs-on: ubuntu-latest
    needs: test_suite_run
    steps:
      - name: Slack Notification if the test suite run on ${{ env.GKE_CLUSTER_NAME }} GKE in ${{ env.DEPLOYMENT_NAME }} namespace succeeded.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testkube-logs
          SLACK_COLOR: ${{ needs.test_suite_run.result }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Test suite successfully run on ${{ env.GKE_CLUSTER_NAME }} GKE in ${{ env.DEPLOYMENT_NAME }} namespace :party_blob:!
          SLACK_USERNAME: GitHub
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Kubeshop --> TestKube"

  notify_slack_if_test_suite_failed:
    runs-on: ubuntu-latest
    needs: test_suite_run
    if: always() && (needs.test_suite_run.result == 'failure')
    steps:
      - name: Slack Notification if the test suite run on ${{ env.GKE_CLUSTER_NAME }} GKE in ${{ env.DEPLOYMENT_NAME }} namespace failed.
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: testkube-logs
          SLACK_COLOR: ${{ needs.test_suite_run.result }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Test suite FAILED to run on ${{ env.GKE_CLUSTER_NAME }} GKE in ${{ env.DEPLOYMENT_NAME }} namespace! :boom:!
          SLACK_USERNAME: GitHub
          SLACK_LINK_NAMES: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Kubeshop --> TestKube"