name: Bump Helm Chart Version for Kusk Gateway charts

on:
  workflow_call:
    inputs:
      appVersion:
        required: true
        type: string

jobs:

  bump_up_chart:
    runs-on: ubuntu-latest

    steps:
      - name: output appVersion
        run: echo ${{ inputs.appVersion }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "kubeshop/helm-charts"
          ref: "main"
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Bump up kusk-gateway chart
        run: |
          #CHART_VERSION=$(sed )
          echo 1

      - name: Push updated chart
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          # git add .
          # git commit -m "automatically updated kusk-gateway related charts"
          # git push



  notify_slack_if_helm_chart_bump_fails:
    runs-on: ubuntu-latest
    needs: bump_up_chart
    if: always() && (needs.bump_up_chart.result == 'failure')
    steps:
    - name: Slack Notification if Helm Release action failed
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: testmessages
        SLACK_COLOR: ${{ needs.bump_up_chart.result }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Helm Chart version bump action failed :boom:!
        SLACK_USERNAME: GitHub
        SLACK_LINK_NAMES: true
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: "Kubeshop --> Kusk Gateway"

  notify_slack_if_version_bump_succeeds:
    runs-on: ubuntu-latest
    needs: bump_up_chart
    steps:
    - name: Slack Notification if the helm version bump pipeline succeeded.
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: testmessages
        SLACK_COLOR: ${{ needs.bump_up_chart.result }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Helm chart version bump succeeded :party_blob:!
        SLACK_USERNAME: GitHub
        SLACK_LINK_NAMES: true
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: "Kubeshop --> Kusk Gateway"
