name: Lint images

on: push

jobs:
  lint-images:
    name: Lint images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check that global.imageRegistry is applied to all images
        run: bash ./image_registry_check.sh
        working-directory: ./scripts

      - name: Check that global.imagePullSecrets are applied to all images
        run: bash ./image_pull_secrets_check.sh
        working-directory: ./scripts
