name: Lint images

on: push

jobs:
  lint-images:
    name: Lint images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check that global.imageRegistry is applied to all images
        run: bash ./image_registry_check.sh
        working-directory: ./scripts

      - name: Check that global.imagePullSecrets are applied to all images
        run: bash ./image_pull_secrets_check.sh
        working-directory: ./scripts

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      - name: Check to make sure that images do not have critical CVEs
        run: bash ./image_cve_check.sh
        working-directory: ./scripts
